public class Practice {
    
    public Practice (){
        system.debug('Hey im in Modified Class by DeOoops');
    }
    
    public void Method1(){
        integer a=10;
        integer b= 6;
        integer Re= a+b;
        system.debug(' Non paramatrized constructor==> Addioon is'+re);
                    
        } 
    public void DevOops(integer a, integer b){
       Integer re= a+b;
        system.debug('Non Pramatrized==> addition'+re);
        
    }
	public void devOops (){
		system.debug('Hey im in Modified Class by DeOoops');
	}
	
	public void DevOops(integer a, integer b){
       Integer re= a+b;
        system.debug('Non Pramatrized==> addition'+re);
        
    }
	public void devOops (){
		system.debug('Hey im in Modified Class by DeOoops');
	}
}